#ifndef LIBXLSXWRITER_GLOBAL_H
#define LIBXLSXWRITER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBXLSXWRITER_LIBRARY)
#  define LIBXLSXWRITERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBXLSXWRITERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBXLSXWRITER_GLOBAL_H
